---
title: "UCRB map figure prep"
author: "cbrung"
date: "March 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


2.3 Spatial plotting on UCRB boundary.
ggplot method
All code modified from: https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-2.html
```{r}
#install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", "ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))

library("ggplot2")
 theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("maps")
library("tools")
library("ggspatial")

# Get country boundaries 
world <- ne_countries(scale = "medium", returnclass = "sf")
world.a <- st_transform(world, '+init=epsg:5070')

# Read in training and validation observations.
t.dc2 <- read.csv("Z:/UCRB/Observations/t.dc2.csv")
v.dc3 <- read.csv("Z:/UCRB/Observations/v.dc3.csv")

# Convert training and validation observations to 'sf'.
t.dc2 <- st_as_sf(t.dc2, coords = c("x", "y"), crs = 5070, agr = "constant")
v.dc3 <- st_as_sf(v.dc3, coords = c("x", "y"), crs = 5070, agr = "constant")

# Get a shapefile of US states, then create points at the center of each state (for plotting labels)
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
states <- cbind(states, st_coordinates(st_centroid(states)))

# Capitilize state names and reproject
states$ID <- toTitleCase(states$ID)
states.a <- st_transform(states,'+init=epsg:5070')

# Project Area Boundary. Convert to 'sf' form
UCRBbound <- readOGR(dsn="Z:/UCRB/Boundaries", layer = "CO_River_watershed_Meade_wgs84")
ucrbbound.sf <- st_as_sf(UCRBbound)

# Plot
# dont know why this won't plot the legend of the points. 
ggplot(data = world) +
    geom_sf() +
    geom_sf(data = states, fill = NA) +
    geom_sf(data = ucrbbound.sf, fill = NA, col = 'blue') +
    geom_text(data = states, aes(X, Y, label = ID), size = 2) +
    geom_sf(data = t.dc2, shape = 3, col = "darkolivegreen", show.legend = TRUE) + 
    geom_sf(data = v.dc3, shape = 4, col = "darkgoldenrod", show.legend = TRUE) +
    annotation_scale(location = "bl", width_hint = 0.4, style = 'ticks') +
    annotation_north_arrow(location = "bl", which_north = "true", 
                           pad_x = unit(0.25, "in"), pad_y = unit(0.25, "in"),
                           style = north_arrow_minimal) +
    coord_sf(xlim = c(-120, -100), ylim = c(30, 45), expand = FALSE) + 
    xlab("Longitude") + ylab("Latitude") +
    ggtitle("Upper Colorado River Basin") + 
    theme(panel.grid.major = element_blank())
ggsave("Z:/UCRB/Figures/train_test_studyarea.png")
```




MLRA, UCRB, Landform
This is cool, but it is so much easier to get the labels right in QGIS that I did that. 
```{r}
library(rgdal)
mlra.b <- readOGR(dsn="Z:/UCRB/Boundaries", layer = "CO_River_watershed_Meade_NAD83_MLRA_dissolve1")
mlra.sf <- st_as_sf(mlra.b)
# Make points for labels to locate them on the graph 
mlra.sf <- cbind(mlra.sf, st_coordinates(st_centroid(mlra.sf)))

library("ggrepel")

ggplot(data = world) +
    geom_sf() +
    geom_sf(data = states, fill = NA) +
    geom_sf(data = ucrbbound.sf, fill = NA, col = 'blue') +
    geom_sf(data = mlra.sf, aes(col = MLRA_NAME), show.legend = FALSE) +
    geom_text_repel(data = mlra.sf, aes(x = X, y = Y, label = MLRA_NAME), size = 2, 
                    nudge_x = c(0, 0, 0, 3, -2, -3,-4.5, 1.5,-4.5), nudge_y = c(0,0.5,0,-0.25,0,0,0,0,0)) + 
    coord_sf(xlim = c(-120, -100), ylim = c(30, 45), expand = FALSE) + 
    xlab("Longitude") + ylab("Latitude") +
    ggtitle("Major Land Resource Areas (MLRA)") 
ggsave("Z:/UCRB/Figures/MLRA_in_studyarea.png")
  

# The Iwahashi landforms are raster format. Plot them
library(raster)
library("RColorBrewer")
#Iwahashi landform raster
ras <- raster("Z:/UCRB/Covariates/TravisCovariates/iwahashiLF_m.tif") 

# Good colors
colr=brewer.pal(n = 4, name = "Accent")

# add breaks to the colormap 
brk <- c(1,4,6,8,15)

png("Z:/UCRB/Figures/IWLF_in_studyarea.png", bg = "transparent", res=100)
# Set up margins ( I think it is bottom, left, top, right)
par(xpd = FALSE, mar=c(3, 3, 3, 10))
# Plot
plot(ras, col=colr, breaks=brk, main="Iwahashi Landforms", legend = FALSE)
#add a legend - but make it appear outside of the plot
par(xpd = TRUE)
legend(par()$usr[2], 1800000,
        legend = c("Bedrock mountain", "Hills", "Large highland slope", "Plateau"), 
        fill = colr)
dev.off()
```






Graticule map for reference. 
https://www.rdocumentation.org/packages/sf/versions/0.7-2/topics/st_graticule

doesn't work like I want
```{r}
library(sf)
library(maps)

usa = st_as_sf(map('usa', plot = FALSE, fill = FALSE))
laea = st_crs("+proj=laea +lat_0=30 +lon_0=-95") # Lambert equal area
usa <- st_transform(usa, laea)

bb = st_bbox(usa)
bbox = st_linestring(rbind(c( bb[1],bb[2]),c( bb[3],bb[2]),
   c( bb[3],bb[4]),c( bb[1],bb[4]),c( bb[1],bb[2])))

g = st_graticule(usa)
plot(usa, xlim = 1.2 * c(-2450853.4, 2186391.9))
plot(g[1], add = TRUE, fill = FALSE)
plot(bbox, add = TRUE)
points(g$x_start, g$y_start, col = 'red')
points(g$x_end, g$y_end, col = 'blue')

invisible(lapply(seq_len(nrow(g)), function(i) {
if (g$type[i] == "N" && g$x_start[i] - min(g$x_start) < 1000)
	text(g[i,"x_start"], g[i,"y_start"], labels = parse(text = g[i,"degree_label"]),
		srt = g$angle_start[i], pos = 2, cex = .7)
if (g$type[i] == "E" && g$y_start[i] - min(g$y_start) < 1000)
	text(g[i,"x_start"], g[i,"y_start"], labels = parse(text = g[i,"degree_label"]),
		srt = g$angle_start[i] - 90, pos = 1, cex = .7)
if (g$type[i] == "N" && g$x_end[i] - max(g$x_end) > -1000)
	text(g[i,"x_end"], g[i,"y_end"], labels = parse(text = g[i,"degree_label"]),
		srt = g$angle_end[i], pos = 4, cex = .7)
if (g$type[i] == "E" && g$y_end[i] - max(g$y_end) > -1000)
	text(g[i,"x_end"], g[i,"y_end"], labels = parse(text = g[i,"degree_label"]),
		srt = g$angle_end[i] - 90, pos = 3, cex = .7)
}))
plot(usa, graticule = st_crs(4326), axes = TRUE, lon = seq(-60,-130,by=-10))
# }
```












